# Generated by Django 5.2.3 on 2025-06-30 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('whatsInclude', models.TextField(null=True)),
                ('forWhom', models.TextField(null=True)),
                ('status', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
