# Generated by Django 5.1.7 on 2025-03-06 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 7, 4, 3, 23, 164796))),
                ('updated_at', models.DateField()),
                ('is_delete', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
            ],
        ),
    ]
