# WHILE LOOP 


# while (condition):
#     code 

# a = 1
# while a<=10:
#     print("hello")
#     a += 1 


# a = 10
# while a>=1:
#     print("hello",a)
#     a -= 1 


# =========================

# con = "yes"

# while con=="yes":
#     a = int(input("enter a number = "))
#     b = int(input("enter a number = "))
#     print(f"{a} + {b} = {a+b}")
#     # print(a,"+",b,"=",a+b)
#     con = input("do you want to continue = ")

# ==============================


# enter a -ve number = 43
# enter a -ve number = 8
# enter a -ve number = 23
# enter a -ve number = -3

# thank for entring -ve number 

# ======================================
# i = 0
# a = 9 
# while i<a:
#     a = int(input("enter a number = ")) 
#     if(a<0):
#         print("thank you")



# num = 43
# while(num>=0):
#     num = int(input("enter a -ve number = "))

# print("thank you ")

# get values from user and print counting from 1 to that number
# get value from user and print the table 
# print all even numbers from 1 to 100
# count all leap years from 1500 to 2023
# get value from user and print total sum from 1 to that number
# get value from user and print factorial
# Get 2 values from user and print addition till answer is zero(0)
# get values from user till 0 and print total addition of all numbers

# enter a number = 4
# enter a number = 3
# enter a number = 7
# enter a number = 3
# enter a number = 0
# sum = 21 
# =============================================

# num = int(input("enter a number = "))
# ans = 1 
# while (num>=1):
#     ans = ans * num 
#     num -= 1 
# print(ans)


# ans = 4
# while (ans>0 or ans<0):
#     a = int(input("enter a number = "))
#     b = int(input("enter a number = "))
#     ans = a + b
#     print(ans)



