# Generated by Django 5.2.1 on 2025-05-15 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeraPati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('job', models.CharField(max_length=255)),
                ('maritialStatus', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('spiritual', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('vegitarian', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('supportive', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('loyal', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('trustable', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('carring', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('mature', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('childish', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('fit', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='0', max_length=1)),
                ('salary', models.IntegerField()),
                ('tech_strong', models.CharField(choices=[('0', 'fresher'), ('1', 'mediam'), ('2', 'experianced')], max_length=1)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
